### ISSUE TITLE
WELCOME to the new issue

### ISSUE THREAD

**Issue by nyanme** [nyanme/The-Special-stuff-for-suspect#3]
The issue is us. we have creepy spooky and so scary problems. help

**Comment by nyanme** [comment]
I WILL NOT KILL MYSELF BY THE WAY!

**Comment by PaixD** [comment]
kill ur self my friend

Term Paper -- Due date [22/06/18]
Ageing Population

Describe the demographics of the country you are now in
1. Definition of terms
2. Characteristics of  the Population
3. Populations distributions and density acording to countries and reasons for that
4. Use statistics , maps and graphs

**Comment by nyanme** [comment]
ok

**Comment by nyanme** [comment]
butt what is the terms?
